import { db } from '../src/lib/db'

const CENTER = { lat: 28.6139, lng: 77.209 }

function jitter(base: number, amount: number) {
  return base + (Math.random() - 0.5) * amount
}

// B2B-only categories — no consumer-facing businesses
const categories = [
  { name: 'Manufacturers', slug: 'manufacturers', icon: 'Factory', color: '#0f766e' },
  { name: 'Industrial Machinery', slug: 'industrial-machinery', icon: 'Cog', color: '#475569' },
  { name: 'Wholesalers & Distributors', slug: 'wholesalers-distributors', icon: 'Package', color: '#0891b2' },
  { name: 'Industrial Supplies', slug: 'industrial-supplies', icon: 'Wrench', color: '#1d4ed8' },
  { name: 'Raw Materials & Commodities', slug: 'raw-materials', icon: 'Boxes', color: '#b45309' },
  { name: 'Packaging & Printing', slug: 'packaging-printing', icon: 'Package', color: '#7c3aed' },
  { name: 'Logistics & Supply Chain', slug: 'logistics', icon: 'Truck', color: '#0891b2' },
  { name: 'IT & Software Services', slug: 'it-software', icon: 'Monitor', color: '#4338ca' },
  { name: 'Construction & Building Materials', slug: 'construction-materials', icon: 'Building', color: '#dc2626' },
  { name: 'Agricultural Equipment', slug: 'agricultural-equipment', icon: 'Sprout', color: '#65a30d' },
  { name: 'Textile & Garments', slug: 'textile-garments', icon: 'Shirt', color: '#db2777' },
  { name: 'Electronics & Components', slug: 'electronics-components', icon: 'CircuitBoard', color: '#1f2937' },
  { name: 'Chemicals & Plastics', slug: 'chemicals-plastics', icon: 'FlaskConical', color: '#0d9488' },
  { name: 'Import & Export', slug: 'import-export', icon: 'Ship', color: '#ca8a04' },
]

const img = (seed: string, w = 800, h = 600) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`

const CATEGORY_IMAGE_SEEDS: Record<string, string[]> = {
  Manufacturers: ['factory', 'manufacturing', 'production', 'mill', 'grain', 'processing'],
  'Industrial Machinery': ['machinery', 'cnc', 'industrial', 'workshop', 'metalwork', 'engineering'],
  'Wholesalers & Distributors': ['warehouse', 'logistics', 'wholesale', 'distribution', 'storage', 'supply'],
  'Industrial Supplies': ['bearings', 'tools', 'hardware', 'industrial', 'supply', 'equipment'],
  'Raw Materials & Commodities': ['steel', 'metal', 'mineral', 'commodity', 'material', 'industrial'],
  'Packaging & Printing': ['packaging', 'printing', 'box', 'label', 'cardboard', 'wrap'],
  'Logistics & Supply Chain': ['truck', 'transport', 'freight', 'shipping', 'warehouse', 'container'],
  'IT & Software Services': ['computer', 'software', 'technology', 'server', 'data', 'coding'],
  'Construction & Building Materials': ['cement', 'steel', 'construction', 'building', 'brick', 'concrete'],
  'Agricultural Equipment': ['tractor', 'agriculture', 'farm', 'irrigation', 'harvester', 'agro'],
  'Textile & Garments': ['fabric', 'textile', 'garment', 'cotton', 'weaving', 'fashion'],
  'Electronics & Components': ['circuit', 'electronics', 'pcb', 'component', 'chip', 'board'],
  'Chemicals & Plastics': ['chemical', 'plastic', 'polymer', 'laboratory', 'industrial', 'compound'],
  'Import & Export': ['shipping', 'trade', 'export', 'import', 'container', 'port'],
}

function categorySeed(category: string, index: number): string {
  const seeds = CATEGORY_IMAGE_SEEDS[category] || ['business', 'office', 'commercial', 'industrial', 'warehouse', 'company']
  return seeds[index % seeds.length]
}

const businesses = [
  {
    name: 'Shakti Rice & Flour Mills',
    tagline: 'B2B grain processing & bulk supply since 1972',
    description: 'Shakti Mills is a third-generation agro-processing enterprise producing premium rice, atta, besan and bespoke flour blends for wholesalers, FMCG brands and export houses. Our automated 40 TPD plant services B2B clients with consistent granularity, moisture control and hygiene-certified packaging.',
    category: 'Manufacturers',
    verified: 'premium',
    rating: 4.5,
    reviewCount: 318,
    area: 'Industrial Area Phase II',
    foundedYear: 1972,
    teamSize: '120',
    brandColor: '#0f766e',
    trending: true,
    featured: true,
    subCategories: ['Rice Milling', 'Flour Milling', 'Agro Processing', 'Packaged Foods'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['Cash', 'UPI', 'NEFT', 'RTGS', 'Credit (verified buyers)'],
    facilities: ['40 TPD plant', 'Cold storage', 'Lab testing', 'Loading bay', 'GST warehouse'],
    deliveryOptions: ['Pan-India transport', 'Container export', 'FCL/LCL'],
    certifications: ['FSSAI', 'ISO 22000', 'APEDA Exporter'],
    awards: ['Top Agro Exporter 2023'],
    products: [
      { name: 'Sona Masoori Rice (Premium)', category: 'Rice', brand: 'Shakti Gold', priceMin: 52, priceMax: 58, availability: 'in_stock', featured: true, variants: ['5kg', '10kg', '25kg', '50kg'], specifications: [{ label: 'Grain length', value: '5.8mm' }, { label: 'Moisture', value: '<13%' }, { label: 'Broken', value: '<2%' }] },
      { name: 'Automatic Flour Mill Machine 30 TPD', category: 'Industrial Machinery', brand: 'Shakti Tech', priceMin: 1850000, priceMax: 2400000, availability: 'made_to_order', featured: true, variants: ['Chakki', 'Roller', 'Pulverizer'], specifications: [{ label: 'Capacity', value: '30 TPD' }, { label: 'Power', value: '75 kW' }, { label: 'Warranty', value: '2 years' }] },
      { name: 'Whole Wheat Atta (Stone Ground)', category: 'Flour', brand: 'Shakti Pure', priceMin: 38, priceMax: 44, availability: 'in_stock', variants: ['1kg', '5kg', '10kg', '30kg'], specifications: [{ label: 'Extraction', value: '95%' }, { label: 'Ash content', value: '<1.5%' }] },
      { name: 'Besan (Gram Flour)', category: 'Flour', brand: 'Shakti Pure', priceMin: 75, priceMax: 90, availability: 'low_stock', variants: ['500g', '1kg', '5kg'], specifications: [{ label: 'Protein', value: '22%' }] },
    ],
    services: [
      { name: 'Custom Flour Blending', pricing: 'On quote', duration: '3–7 days', coverageArea: 'Pan-India', deliverables: ['Formulation', 'Pilot batch', 'Production run'] },
    ],
  },
  {
    name: 'Nexus Precision Engineering',
    tagline: 'CNC machining for B2B industrial clients',
    description: 'Nexus Precision manufactures high-tolerance components for aerospace, defense and medical device OEMs. Our climate-controlled facility houses 5-axis machining centers, Swiss-type lathes and CMM inspection, enabling tolerances down to ±5 microns.',
    category: 'Industrial Machinery',
    verified: 'enterprise',
    rating: 4.8,
    reviewCount: 92,
    area: 'Industrial Area Phase I',
    foundedYear: 2008,
    teamSize: '80',
    brandColor: '#475569',
    featured: true,
    subCategories: ['CNC Machining', 'Fabrication', 'Tool Room', 'Quality Inspection'],
    languages: ['English'],
    paymentMethods: ['NEFT', 'RTGS', 'Letter of Credit'],
    facilities: ['5-axis CNC', 'Swiss lathe', 'CMM', 'EDM', 'Climate-controlled bay'],
    deliveryOptions: ['Pan-India', 'Export'],
    certifications: ['ISO 9001', 'AS9100D', 'ISO 13485'],
    awards: ['Aerospace Supplier of the Year 2022'],
    products: [
      { name: 'Stainless Steel Storage Tank 5000L', category: 'Tanks & Vessels', brand: 'NexusVessel', priceMin: 185000, priceMax: 320000, availability: 'made_to_order', featured: true, variants: ['SS304', 'SS316', 'Jacketed'], specifications: [{ label: 'Capacity', value: '5000 L' }, { label: 'Material', value: 'SS316L' }, { label: 'Pressure', value: '3 bar' }, { label: 'Finish', value: 'Mirror polish' }] },
      { name: 'Precision Machined Component (Custom)', category: 'Machined Parts', brand: 'Nexus', priceMin: 350, priceMax: 0, availability: 'made_to_order', variants: ['As per drawing'], specifications: [{ label: 'Tolerance', value: '±5 microns' }, { label: 'Material', value: 'Al / SS / Ti' }] },
    ],
    services: [
      { name: '5-Axis CNC Machining', pricing: 'From ₹1,200/hour', duration: '1–15 days', coverageArea: 'Global', deliverables: ['Finished parts', 'FAI report', 'CMM report'] },
      { name: 'Reverse Engineering', pricing: '₹15,000 – ₹80,000', duration: '3–7 days', coverageArea: 'Global', deliverables: ['3D model', 'Drawing pack', 'Prototype'] },
    ],
  },
  {
    name: 'Apex Wholesale Distributors',
    tagline: 'B2B FMCG distribution at scale',
    description: 'Apex is a leading B2B distributor for 40+ FMCG brands, servicing 6,000 retailers across three states with a 60-vehicle fleet and 4 warehouses. Real-time stock visibility for partners.',
    category: 'Wholesalers & Distributors',
    verified: 'premium',
    rating: 4.3,
    reviewCount: 156,
    area: 'Logistics Hub',
    foundedYear: 1995,
    teamSize: '180',
    brandColor: '#0891b2',
    subCategories: ['FMCG', 'Beverages', 'Personal Care'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit'],
    facilities: ['4 warehouses', 'Cold storage', '60 vehicles'],
    deliveryOptions: ['3-state network'],
    certifications: ['GST', 'FSSAI'],
    products: [
      { name: 'Packaged Drinking Water (1L x 12)', category: 'Beverages', brand: 'AquaPure', priceMin: 96, priceMax: 120, availability: 'in_stock', variants: ['12x1L', '24x500ml'], specifications: [{ label: 'Shelf life', value: '12 months' }] },
    ],
    services: [],
  },
  {
    name: 'Bharat Industrial Supplies',
    tagline: 'Bearings, tools & industrial hardware wholesale',
    description: 'Bharat Industrial Supplies is a leading B2B distributor of bearings, power transmission products, industrial tools and hardware. Authorized dealer for SKF, FAG, Timken and Bosch. Serving 2000+ factories and workshops.',
    category: 'Industrial Supplies',
    verified: 'verified',
    rating: 4.4,
    reviewCount: 203,
    area: 'Industrial Market',
    foundedYear: 1985,
    teamSize: '65',
    brandColor: '#1d4ed8',
    trending: true,
    subCategories: ['Bearings', 'Power Transmission', 'Industrial Tools', 'Safety Equipment'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30/60/90)'],
    facilities: ['Warehouse', 'Testing lab', 'Counter sales'],
    deliveryOptions: ['Pan-India', 'Same-day city delivery'],
    certifications: ['ISO 9001', 'SKF Authorized'],
    products: [
      { name: 'SKF Deep Groove Ball Bearing 6205', category: 'Bearings', brand: 'SKF', priceMin: 180, priceMax: 350, availability: 'in_stock', featured: true, variants: ['6205-2RS', '6205-ZZ', '6205-Open'], specifications: [{ label: 'Bore', value: '25mm' }, { label: 'OD', value: '52mm' }, { label: 'Width', value: '15mm' }] },
      { name: 'Bosch Professional Drill GSB 550', category: 'Power Tools', brand: 'Bosch', priceMin: 3200, priceMax: 4500, availability: 'in_stock', variants: ['With case', 'Bare tool'], specifications: [{ label: 'Power', value: '550W' }, { label: 'Chuck', value: '13mm' }] },
      { name: 'Industrial Safety Helmet (ISI)', category: 'Safety Equipment', brand: 'Karam', priceMin: 120, priceMax: 180, availability: 'in_stock', variants: ['White', 'Yellow', 'Blue', 'Red'], specifications: [{ label: 'Standard', value: 'IS 2925' }] },
    ],
    services: [],
  },
  {
    name: 'SteelCorp Raw Materials',
    tagline: 'B2B steel, metals & industrial raw materials',
    description: 'SteelCorp supplies MS flats, rounds, sheets, SS coils and structural steel to fabrication units, construction companies and OEM manufacturers. Direct mill pricing with cut-to-size service.',
    category: 'Raw Materials & Commodities',
    verified: 'premium',
    rating: 4.2,
    reviewCount: 145,
    area: 'Steel Market',
    foundedYear: 1978,
    teamSize: '90',
    brandColor: '#b45309',
    featured: true,
    subCategories: ['Mild Steel', 'Stainless Steel', 'Structural Steel', 'Non-Ferrous Metals'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Letter of Credit'],
    facilities: ['Yard', 'Cutting facility', 'Crane', 'Weighbridge'],
    deliveryOptions: ['Pan-India transport', 'FCL/LCL container'],
    certifications: ['BIS Certified', 'ISO 9001'],
    products: [
      { name: 'MS Flat 50x6mm (per meter)', category: 'Mild Steel', brand: 'SteelCorp', priceMin: 85, priceMax: 120, availability: 'in_stock', featured: true, variants: ['50x6', '75x8', '100x10'], specifications: [{ label: 'Grade', value: 'IS 2062 E250' }, { label: 'Length', value: '6m std' }] },
      { name: 'SS 304 Sheet 2B Finish (per sq ft)', category: 'Stainless Steel', brand: 'SteelCorp', priceMin: 180, priceMax: 250, availability: 'in_stock', variants: ['0.8mm', '1mm', '1.5mm', '2mm', '3mm'], specifications: [{ label: 'Grade', value: 'SS 304' }, { label: 'Finish', value: '2B' }] },
    ],
    services: [],
  },
  {
    name: 'PrintPack Solutions',
    tagline: 'B2B packaging & printing solutions',
    description: 'PrintPack manufactures corrugated boxes, flexible packaging, labels and printed materials for FMCG, pharma and e-commerce brands. In-house flexo and offset printing with quick turnaround.',
    category: 'Packaging & Printing',
    verified: 'verified',
    rating: 4.5,
    reviewCount: 98,
    area: 'Industrial Area Phase I',
    foundedYear: 2010,
    teamSize: '75',
    brandColor: '#7c3aed',
    trending: true,
    subCategories: ['Corrugated Boxes', 'Flexible Packaging', 'Labels', 'Commercial Printing'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'UPI', 'Credit (30 days)'],
    facilities: ['Flexo press', 'Offset press', 'Die-cutting', 'Lamination'],
    deliveryOptions: ['Pan-India', 'Local same-day'],
    certifications: ['FSSAI', 'ISO 9001'],
    products: [
      { name: '3-Ply Corrugated Box (Custom Size)', category: 'Corrugated Boxes', brand: 'PrintPack', priceMin: 12, priceMax: 45, availability: 'made_to_order', featured: true, variants: ['3-ply', '5-ply', '7-ply', '9-ply'], specifications: [{ label: 'Burst strength', value: '16 kg/cm²' }, { label: 'MOQ', value: '500 units' }] },
      { name: 'Printed Labels (Roll)', category: 'Labels', brand: 'PrintPack', priceMin: 0.5, priceMax: 3, availability: 'made_to_order', variants: ['Paper', 'BOPP', 'Foil'], specifications: [{ label: 'MOQ', value: '10,000' }, { label: 'Colors', value: 'Up to 8' }] },
    ],
    services: [
      { name: 'Custom Packaging Design', pricing: 'From ₹5,000', duration: '3–5 days', coverageArea: 'Pan-India', deliverables: ['Design proof', 'Sample', 'Production run'] },
    ],
  },
  {
    name: 'Transworld Logistics',
    tagline: 'B2B freight, warehousing & supply chain',
    description: 'Transworld provides end-to-end B2B logistics including freight forwarding, warehousing, last-mile delivery and cold chain. 3PL partner for 150+ manufacturers and distributors.',
    category: 'Logistics & Supply Chain',
    verified: 'premium',
    rating: 4.4,
    reviewCount: 167,
    area: 'Logistics Hub',
    foundedYear: 2005,
    teamSize: '350',
    brandColor: '#0891b2',
    featured: true,
    subCategories: ['Freight Forwarding', 'Warehousing', '3PL', 'Cold Chain'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30/60 days)'],
    facilities: ['12 warehouses', 'Fleet of 200 trucks', 'Cold storage', 'Container yard'],
    deliveryOptions: ['Pan-India', 'International'],
    certifications: ['ISO 9001', 'ISO 14001', 'AEO Certified'],
    awards: ['Best 3PL Provider 2023'],
    products: [],
    services: [
      { name: 'Full Truck Load (FTL)', pricing: 'From ₹15/km', duration: '1–5 days', coverageArea: 'Pan-India', deliverables: ['Dedicated truck', 'GPS tracking', 'POD'] },
      { name: 'Warehousing (per pallet/month)', pricing: '₹500 – ₹1,200', duration: 'Monthly', coverageArea: '12 cities', deliverables: ['Storage', 'Inventory management', 'Pick & pack'] },
    ],
  },
  {
    name: 'DataSync IT Services',
    tagline: 'B2B software, cloud & IT infrastructure',
    description: 'DataSync provides enterprise software development, cloud migration, managed IT services and cybersecurity for B2B clients. 200+ enterprise clients across manufacturing, logistics and retail sectors.',
    category: 'IT & Software Services',
    verified: 'verified',
    rating: 4.6,
    reviewCount: 134,
    area: 'IT Park',
    foundedYear: 2012,
    teamSize: '250',
    brandColor: '#4338ca',
    trending: true,
    subCategories: ['Custom Software', 'Cloud Services', 'Cybersecurity', 'Managed IT'],
    languages: ['English'],
    paymentMethods: ['NEFT', 'RTGS', 'Annual contracts'],
    facilities: ['Data center', 'R&D lab', 'Support center'],
    deliveryOptions: ['Remote delivery', 'On-site support'],
    certifications: ['ISO 27001', 'CMMI Level 3', 'AWS Partner'],
    products: [
      { name: 'Enterprise ERP Software (Annual License)', category: 'Software', brand: 'DataSync', priceMin: 150000, priceMax: 500000, availability: 'in_stock', featured: true, variants: ['Basic', 'Professional', 'Enterprise'], specifications: [{ label: 'Users', value: 'Unlimited' }, { label: 'Modules', value: '15+' }, { label: 'Deployment', value: 'Cloud/On-prem' }] },
    ],
    services: [
      { name: 'Custom Software Development', pricing: 'From ₹2,500/hour', duration: 'Project-based', coverageArea: 'Global', deliverables: ['Design', 'Development', 'Testing', 'Support'] },
      { name: 'Cloud Migration & Management', pricing: 'From ₹50,000/month', duration: 'Ongoing', coverageArea: 'Global', deliverables: ['Assessment', 'Migration', 'Optimization', '24/7 support'] },
    ],
  },
  {
    name: 'BuildWell Construction Materials',
    tagline: 'B2B cement, bricks & building materials',
    description: 'BuildWell supplies cement, bricks, TMT steel bars, aggregates and construction chemicals to builders, contractors and infrastructure companies. Bulk pricing with site delivery.',
    category: 'Construction & Building Materials',
    verified: 'verified',
    rating: 4.3,
    reviewCount: 187,
    area: 'Building Materials Market',
    foundedYear: 1998,
    teamSize: '120',
    brandColor: '#dc2626',
    subCategories: ['Cement', 'Bricks & Blocks', 'TMT Steel', 'Aggregates'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30 days)'],
    facilities: ['Yard', 'Testing lab', 'Delivery fleet'],
    deliveryOptions: ['Site delivery', 'Pan-India'],
    certifications: ['BIS Certified', 'ISO 9001'],
    products: [
      { name: 'OPC 53 Grade Cement (50kg bag)', category: 'Cement', brand: 'UltraTech', priceMin: 380, priceMax: 420, availability: 'in_stock', featured: true, variants: ['OPC 53', 'PPC', 'PSC'], specifications: [{ label: 'Grade', value: '53 Grade' }, { label: 'MOQ', value: '100 bags' }] },
      { name: 'TMT Steel Bar Fe 500 (per ton)', category: 'TMT Steel', brand: 'Tiscon', priceMin: 58000, priceMax: 62000, availability: 'in_stock', variants: ['8mm', '10mm', '12mm', '16mm', '20mm', '25mm'], specifications: [{ label: 'Grade', value: 'Fe 500' }, { label: 'Standard', value: 'IS 1786' }] },
    ],
    services: [],
  },
  {
    name: 'AgroTech Equipment',
    tagline: 'B2B agricultural machinery & irrigation systems',
    description: 'AgroTech manufactures and supplies tractors, harvesters, irrigation systems and farm equipment to dealers, FPOs and large farms. Dealer network across 8 states.',
    category: 'Agricultural Equipment',
    verified: 'verified',
    rating: 4.5,
    reviewCount: 112,
    area: 'Agro Industrial Zone',
    foundedYear: 2008,
    teamSize: '180',
    brandColor: '#65a30d',
    subCategories: ['Tractors', 'Harvesters', 'Irrigation Systems', 'Farm Implements'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Dealer finance'],
    facilities: ['Assembly plant', 'R&D center', 'Parts warehouse'],
    deliveryOptions: ['Pan-India dealer network'],
    certifications: ['ISO 9001', 'DBT Approved'],
    products: [
      { name: '50 HP Tractor with Cabin', category: 'Tractors', brand: 'AgroTech', priceMin: 750000, priceMax: 850000, availability: 'in_stock', featured: true, variants: ['45 HP', '50 HP', '60 HP', '75 HP'], specifications: [{ label: 'Engine', value: '3-cyl, 2900cc' }, { label: 'Warranty', value: '5 years / 5000 hrs' }] },
      { name: 'Drip Irrigation System (per acre)', category: 'Irrigation Systems', brand: 'AgroTech', priceMin: 25000, priceMax: 40000, availability: 'made_to_order', variants: ['1 acre', '5 acre', '10 acre'], specifications: [{ label: 'Type', value: 'Drip' }, { label: 'Warranty', value: '7 years' }] },
    ],
    services: [
      { name: 'Annual Maintenance Contract', pricing: 'From ₹15,000/year', duration: 'Annual', coverageArea: 'Pan-India', deliverables: ['Regular service', 'Spare parts', 'Priority support'] },
    ],
  },
  {
    name: 'Vardhman Textile Mills',
    tagline: 'B2B fabric manufacturing & garment supply',
    description: 'Vardhman is a vertically integrated textile mill producing cotton yarn, woven fabric and ready-made garments for export houses, brands and domestic retailers. 500 looms, GOTS certified organic line.',
    category: 'Textile & Garments',
    verified: 'premium',
    rating: 4.4,
    reviewCount: 89,
    area: 'Textile Hub',
    foundedYear: 1965,
    teamSize: '1500',
    brandColor: '#db2777',
    featured: true,
    subCategories: ['Yarn', 'Woven Fabric', 'Garments', 'Organic Textile'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Letter of Credit'],
    facilities: ['500 looms', 'Processing unit', 'Garment unit', 'Testing lab'],
    deliveryOptions: ['Pan-India', 'Export FCL/LCL'],
    certifications: ['GOTS Organic', 'OEKO-TEX', 'ISO 9001'],
    awards: ['Top Textile Exporter 2023'],
    products: [
      { name: '100% Cotton Grey Fabric (per meter)', category: 'Woven Fabric', brand: 'Vardhman', priceMin: 45, priceMax: 85, availability: 'in_stock', featured: true, variants: ['20s', '30s', '40s', '60s'], specifications: [{ label: 'Width', value: '58"' }, { label: 'GSM', value: '120-180' }, { label: 'MOQ', value: '5000m' }] },
      { name: 'Organic Cotton Yarn (per kg)', category: 'Yarn', brand: 'Vardhman Organic', priceMin: 280, priceMax: 350, availability: 'in_stock', variants: ['20s', '30s', '40s'], specifications: [{ label: 'Certification', value: 'GOTS' }, { label: 'MOQ', value: '500 kg' }] },
    ],
    services: [],
  },
  {
    name: 'ChipTech Electronics',
    tagline: 'B2B electronic components & PCB assembly',
    description: 'ChipTech supplies electronic components, PCBs and offers contract manufacturing (EMS) for IoT, automotive and industrial electronics. Authorized distributor for TI, STM and NXP.',
    category: 'Electronics & Components',
    verified: 'verified',
    rating: 4.6,
    reviewCount: 76,
    area: 'Electronics City',
    foundedYear: 2015,
    teamSize: '85',
    brandColor: '#1f2937',
    trending: true,
    subCategories: ['Electronic Components', 'PCB Assembly', 'EMS', 'IoT Modules'],
    languages: ['English'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30/60 days)'],
    facilities: ['SMT lines', 'AOI', 'X-ray inspection', 'ESD warehouse'],
    deliveryOptions: ['Pan-India', 'Global export'],
    certifications: ['ISO 9001', 'IATF 16949', 'ESD Compliant'],
    products: [
      { name: 'STM32F103C8T6 Microcontroller', category: 'Electronic Components', brand: 'STMicroelectronics', priceMin: 120, priceMax: 180, availability: 'in_stock', featured: true, variants: ['LQFP48', 'QFN32'], specifications: [{ label: 'Core', value: 'ARM Cortex-M3' }, { label: 'Flash', value: '64KB' }, { label: 'MOQ', value: '100' }] },
      { name: 'Custom PCB Assembly (per sq inch)', category: 'PCB Assembly', brand: 'ChipTech EMS', priceMin: 15, priceMax: 50, availability: 'made_to_order', variants: ['Single-sided', 'Double-sided', 'Multi-layer'], specifications: [{ label: 'MOQ', value: '100 pcs' }, { label: 'Turnaround', value: '7-15 days' }] },
    ],
    services: [
      { name: 'Electronic Manufacturing Services (EMS)', pricing: 'On quote', duration: '2–6 weeks', coverageArea: 'Global', deliverables: ['Design review', 'PCB fabrication', 'Assembly', 'Testing'] },
    ],
  },
  {
    name: 'ChemCorp Industries',
    tagline: 'B2B industrial chemicals & plastic compounds',
    description: 'ChemCorp manufactures industrial chemicals, plastic compounds, resins and specialty chemicals for pharmaceuticals, textiles, paints and packaging industries. ISO certified with in-house R&D.',
    category: 'Chemicals & Plastics',
    verified: 'premium',
    rating: 4.3,
    reviewCount: 67,
    area: 'Chemical Zone',
    foundedYear: 1990,
    teamSize: '220',
    brandColor: '#0d9488',
    subCategories: ['Industrial Chemicals', 'Plastic Compounds', 'Resins', 'Specialty Chemicals'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Letter of Credit'],
    facilities: ['Manufacturing plant', 'R&D lab', 'Hazardous waste management'],
    deliveryOptions: ['Pan-India', 'Export'],
    certifications: ['ISO 9001', 'ISO 14001', 'REACH Compliant'],
    products: [
      { name: 'Caustic Soda Flakes (per kg)', category: 'Industrial Chemicals', brand: 'ChemCorp', priceMin: 42, priceMax: 55, availability: 'in_stock', featured: true, variants: ['25kg bag', '50kg drum'], specifications: [{ label: 'Purity', value: '99%' }, { label: 'Grade', value: 'Industrial' }] },
      { name: 'PP Plastic Granules (per kg)', category: 'Plastic Compounds', brand: 'ChemCorp', priceMin: 95, priceMax: 120, availability: 'in_stock', variants: ['Natural', 'Black', 'Colored'], specifications: [{ label: 'Grade', value: 'PP Homopolymer' }, { label: 'MFI', value: '12 g/10min' }] },
    ],
    services: [],
  },
  {
    name: 'GlobalTrade Exim',
    tagline: 'B2B import-export & international trade',
    description: 'GlobalTrade facilitates international B2B trade — imports of industrial machinery, electronics and raw materials; exports of textiles, chemicals and agricultural products. Full documentation and logistics support.',
    category: 'Import & Export',
    verified: 'enterprise',
    rating: 4.5,
    reviewCount: 54,
    area: 'Port City',
    foundedYear: 2008,
    teamSize: '60',
    brandColor: '#ca8a04',
    featured: true,
    subCategories: ['Import Services', 'Export Services', 'Trade Finance', 'Customs Clearance'],
    languages: ['English', 'Hindi', 'Mandarin'],
    paymentMethods: ['Letter of Credit', 'NEFT', 'RTGS'],
    facilities: ['Customs bonded warehouse', 'Container yard', 'Documentation center'],
    deliveryOptions: ['Global (FCL/LCL/Air)'],
    certifications: ['IEC Code', 'DGFT Registered', 'FIEO Member'],
    awards: ['Top Export House 2023'],
    products: [],
    services: [
      { name: 'Import Sourcing & Documentation', pricing: '2–5% of invoice value', duration: '2–8 weeks', coverageArea: 'Global', deliverables: ['Supplier sourcing', 'Price negotiation', 'Customs clearance', 'Door delivery'] },
      { name: 'Export Facilitation', pricing: '2–5% of invoice value', duration: '2–6 weeks', coverageArea: 'Global', deliverables: ['Buyer matching', 'Documentation', 'Logistics', 'Payment security'] },
    ],
  },
  {
    name: 'Solaris Energy Solutions',
    tagline: 'B2B solar systems for industry & commerce',
    description: 'Solaris designs and installs rooftop solar systems for factories, warehouses and commercial buildings. EPC services from 10kW to 10MW with 25-year performance warranties and financing options.',
    category: 'Industrial Machinery',
    verified: 'premium',
    rating: 4.5,
    reviewCount: 167,
    area: 'Industrial Area Phase I',
    foundedYear: 2014,
    teamSize: '75',
    brandColor: '#ca8a04',
    trending: true,
    subCategories: ['Solar EPC', 'Solar Water Heaters', 'Energy Storage'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['Cheque', 'NEFT', 'Finance'],
    facilities: ['Design center', 'Warehouse', 'Installation team'],
    deliveryOptions: ['Site installation'],
    certifications: ['MNRE Approved', 'ISO 9001', 'ISO 14001'],
    awards: ['Top Solar Installer 2023'],
    products: [
      { name: 'Rooftop Solar System 100kW (Commercial)', category: 'Solar', brand: 'Solaris', priceMin: 3500000, priceMax: 4500000, availability: 'made_to_order', featured: true, variants: ['50kW', '100kW', '250kW', '500kW'], specifications: [{ label: 'Panels', value: 'Mono PERC 550W' }, { label: 'Inverter', value: 'String' }, { label: 'Warranty', value: '25 years' }] },
    ],
    services: [
      { name: 'Solar Site Assessment', pricing: 'Free', duration: '1 hour', coverageArea: 'Citywide', deliverables: ['Feasibility report', 'System sizing', 'ROI estimate'] },
    ],
  },
  {
    name: 'Annapurna Organic Foods',
    tagline: 'B2B certified organic ingredients supplier',
    description: 'Annapurna produces and supplies certified organic grains, pulses, spices and cold-pressed oils to FMCG brands, exporters and health food companies. Direct partnerships with 200+ organic farms.',
    category: 'Manufacturers',
    verified: 'verified',
    rating: 4.4,
    reviewCount: 156,
    area: 'Agro Park',
    foundedYear: 2015,
    teamSize: '60',
    brandColor: '#65a30d',
    featured: true,
    subCategories: ['Organic Foods', 'Packaged Foods', 'Health Foods'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['UPI', 'NEFT', 'Cash'],
    facilities: ['Processing unit', 'Cold storage', 'Lab testing'],
    deliveryOptions: ['Pan-India', 'Subscription'],
    certifications: ['USDA Organic', 'India Organic', 'FSSAI'],
    products: [
      { name: 'Organic Basmati Rice 5kg', category: 'Rice', brand: 'Annapurna', priceMin: 450, priceMax: 520, availability: 'in_stock', variants: ['1kg', '5kg', '10kg'], specifications: [{ label: 'Type', value: 'Organic' }, { label: 'Grade', value: 'A' }] },
      { name: 'Cold-Pressed Mustard Oil 1L', category: 'Oils', brand: 'Annapurna', priceMin: 180, priceMax: 220, availability: 'in_stock', variants: ['500ml', '1L', '5L'], specifications: [{ label: 'Extraction', value: 'Cold-pressed' }] },
      { name: 'Organic Turmeric Powder 500g', category: 'Spices', brand: 'Annapurna', priceMin: 120, priceMax: 160, availability: 'in_stock', variants: ['200g', '500g', '1kg'], specifications: [{ label: 'Curcumin', value: '5%' }] },
    ],
    services: [],
  },
  {
    name: 'Urban Brew Coffee Roasters',
    tagline: 'B2B coffee supply for cafes & hotels',
    description: 'Urban Brew supplies single-origin roasted coffee beans, cold brew concentrate and equipment to cafes, hotel chains and HoReCa. Roastery with tasting bar and barista training.',
    category: 'Manufacturers',
    verified: 'verified',
    rating: 4.8,
    reviewCount: 92,
    area: 'Industrial Estate',
    foundedYear: 2019,
    teamSize: '18',
    brandColor: '#92400e',
    trending: true,
    subCategories: ['Coffee Roasting', 'Beverage Supply', 'Cafe Equipment'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['UPI', 'Card', 'Cash'],
    facilities: ['Roastery', 'Tasting bar', 'Training room'],
    deliveryOptions: ['Pan-India', 'Subscription'],
    certifications: ['FSSAI'],
    products: [
      { name: 'Arabica Estate Coffee Beans 1kg (B2B)', category: 'Coffee', brand: 'Urban Brew', priceMin: 680, priceMax: 850, availability: 'in_stock', featured: true, variants: ['Light roast', 'Medium roast', 'Dark roast', 'Espresso blend'], specifications: [{ label: 'Origin', value: 'Coorg' }, { label: 'Roast date', value: 'Within 7 days' }, { label: 'MOQ', value: '5kg' }] },
      { name: 'Cold Brew Concentrate 1L (B2B)', category: 'Coffee', brand: 'Urban Brew', priceMin: 320, priceMax: 380, availability: 'in_stock', variants: ['500ml', '1L', '5L'], specifications: [{ label: 'Shelf life', value: '30 days refrigerated' }, { label: 'MOQ', value: '10L' }] },
    ],
    services: [
      { name: 'Barista Training Workshop (B2B)', pricing: '₹3,500/person', duration: '4 hours', coverageArea: 'On-site', deliverables: ['Hands-on training', 'Certificate', 'Coffee kit'] },
    ],
  },
  {
    name: 'TechHub Electronics Wholesale',
    tagline: 'B2B electronics & accessories distributor',
    description: 'TechHub is a leading B2B distributor of mobile accessories, computer peripherals and smart home devices. Authorized distributor for 30+ brands, serving 4000+ retailers with next-day delivery.',
    category: 'Wholesalers & Distributors',
    verified: 'premium',
    rating: 4.3,
    reviewCount: 198,
    area: 'Electronics Market',
    foundedYear: 2012,
    teamSize: '85',
    brandColor: '#4338ca',
    subCategories: ['Mobile Accessories', 'Computer Peripherals', 'Smart Home'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit'],
    facilities: ['Warehouse', 'Testing lab', 'Service center'],
    deliveryOptions: ['Next-day delivery', 'Pan-India'],
    certifications: ['GST', 'ISO 9001'],
    products: [
      { name: 'Fast Charging USB-C Cable (Type-C) x100', category: 'Accessories', brand: 'TechConnect', priceMin: 1800, priceMax: 2400, availability: 'in_stock', variants: ['1m', '2m', 'Braided'], specifications: [{ label: 'MOQ', value: '100 units' }, { label: 'Warranty', value: '6 months' }] },
      { name: 'Bluetooth Earbuds Pro (Bulk x50)', category: 'Audio', brand: 'SoundMax', priceMin: 35000, priceMax: 42000, availability: 'in_stock', featured: true, variants: ['Box of 50'], specifications: [{ label: 'MOQ', value: '50 units' }] },
    ],
    services: [],
  },
  {
    name: 'ProClean Industrial Chemicals',
    tagline: 'B2B industrial cleaning & maintenance chemicals',
    description: 'ProClean manufactures industrial cleaning chemicals, degreasers, descalers and maintenance chemicals for factories, food processing units and commercial facilities. Custom formulations available.',
    category: 'Chemicals & Plastics',
    verified: 'verified',
    rating: 4.4,
    reviewCount: 45,
    area: 'Chemical Zone',
    foundedYear: 2010,
    teamSize: '40',
    brandColor: '#0d9488',
    recentlyVerified: true,
    subCategories: ['Industrial Cleaners', 'Degreasers', 'Descalers', 'Disinfectants'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'UPI'],
    facilities: ['Manufacturing unit', 'R&D lab', 'QA testing'],
    deliveryOptions: ['Pan-India'],
    certifications: ['ISO 9001', 'NSF Certified'],
    products: [
      { name: 'Heavy Duty Industrial Degreaser (5L)', category: 'Industrial Cleaners', brand: 'ProClean', priceMin: 450, priceMax: 650, availability: 'in_stock', featured: true, variants: ['5L', '20L', '50L', '200L drum'], specifications: [{ label: 'Dilution', value: '1:10' }, { label: 'Type', value: 'Alkaline' }] },
      { name: 'Food-Safe Surface Sanitizer (5L)', category: 'Disinfectants', brand: 'ProClean', priceMin: 380, priceMax: 500, availability: 'in_stock', variants: ['5L', '20L'], specifications: [{ label: 'Certification', value: 'NSF' }, { label: 'Contact time', value: '30 sec' }] },
    ],
    services: [
      { name: 'Custom Chemical Formulation', pricing: 'On quote', duration: '2–4 weeks', coverageArea: 'Pan-India', deliverables: ['Formulation', 'Sample', 'Production run', 'Safety data sheet'] },
    ],
  },
  {
    name: 'SafeGuard Industrial Safety',
    tagline: 'B2B industrial safety equipment & PPE',
    description: 'SafeGuard supplies PPE, safety equipment and industrial hygiene products to factories, construction sites and mining operations. ISI-certified products with bulk pricing.',
    category: 'Industrial Supplies',
    verified: 'verified',
    rating: 4.5,
    reviewCount: 78,
    area: 'Industrial Market',
    foundedYear: 2015,
    teamSize: '35',
    brandColor: '#1d4ed8',
    subCategories: ['PPE', 'Safety Equipment', 'Industrial Hygiene', 'Fire Safety'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30 days)'],
    facilities: ['Warehouse', 'Testing facility'],
    deliveryOptions: ['Pan-India'],
    certifications: ['BIS Certified', 'ISO 9001'],
    products: [
      { name: 'ISI Safety Helmet (Bulk x100)', category: 'PPE', brand: 'SafeGuard', priceMin: 9500, priceMax: 15000, availability: 'in_stock', featured: true, variants: ['White', 'Yellow', 'Blue', 'Red'], specifications: [{ label: 'Standard', value: 'IS 2925' }, { label: 'MOQ', value: '100' }] },
      { name: 'Safety Harness Full Body (per unit)', category: 'Safety Equipment', brand: 'SafeGuard', priceMin: 1200, priceMax: 2500, availability: 'in_stock', variants: ['Single lanyard', 'Double lanyard', 'With shock absorber'], specifications: [{ label: 'Standard', value: 'IS 3521' }] },
    ],
    services: [],
  },
  {
    name: 'FlexiPak Flexible Packaging',
    tagline: 'B2B flexible packaging & laminates',
    description: 'FlexiPak manufactures flexible packaging films, laminates, pouches and shrink wraps for food, pharma and personal care brands. 8-color printing with custom barrier properties.',
    category: 'Packaging & Printing',
    verified: 'verified',
    rating: 4.6,
    reviewCount: 63,
    area: 'Industrial Area Phase II',
    foundedYear: 2013,
    teamSize: '95',
    brandColor: '#7c3aed',
    subCategories: ['Flexible Films', 'Laminates', 'Pouches', 'Shrink Wraps'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30 days)'],
    facilities: ['8-color press', 'Lamination', 'Slitting', 'Pouch making'],
    deliveryOptions: ['Pan-India'],
    certifications: ['FSSAI', 'ISO 9001'],
    products: [
      { name: 'Stand-Up Pouch (Custom Print)', category: 'Pouches', brand: 'FlexiPak', priceMin: 2.5, priceMax: 8, availability: 'made_to_order', featured: true, variants: ['100g', '250g', '500g', '1kg'], specifications: [{ label: 'MOQ', value: '10,000 pcs' }, { label: 'Colors', value: 'Up to 8' }, { label: 'Barrier', value: 'Custom' }] },
      { name: 'BOPP Laminated Film (per kg)', category: 'Laminates', brand: 'FlexiPak', priceMin: 180, priceMax: 280, availability: 'in_stock', variants: ['12mic', '15mic', '20mic'], specifications: [{ label: 'MOQ', value: '500 kg' }] },
    ],
    services: [],
  },
  // === Additional B2B businesses ===
  {
    name: 'MetalForge Castings',
    tagline: 'B2B investment castings & foundry',
    description: 'MetalForge produces precision investment castings, sand castings and die castings for automotive, valve and pump manufacturers. IS 2062 steel, SS316, and exotic alloys. In-house machining and NDT testing.',
    category: 'Industrial Machinery',
    verified: 'verified',
    rating: 4.4,
    reviewCount: 43,
    area: 'Foundry Estate',
    foundedYear: 1995,
    teamSize: '150',
    brandColor: '#92400e',
    subCategories: ['Investment Castings', 'Sand Castings', 'Die Castings', 'Machining'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'LC'],
    facilities: ['Foundry', 'Machining shop', 'NDT lab', 'Heat treatment'],
    deliveryOptions: ['Pan-India', 'Export'],
    certifications: ['ISO 9001', 'IATF 16949'],
    products: [
      { name: 'SS316 Investment Casting (per kg)', category: 'Castings', brand: 'MetalForge', priceMin: 350, priceMax: 600, availability: 'made_to_order', featured: true, variants: ['SS316', 'SS304', 'Carbon steel'], specifications: [{ label: 'MOQ', value: '100 kg' }, { label: 'Tolerance', value: '±0.1mm' }] },
    ],
    services: [],
  },
  {
    name: 'PowerLine Electricals',
    tagline: 'B2B electrical equipment & transformers',
    description: 'PowerLine manufactures distribution transformers, switchgear, cable trays and industrial electrical panels for utilities, factories and infrastructure projects. BIS certified with 5-year warranty.',
    category: 'Industrial Supplies',
    verified: 'premium',
    rating: 4.5,
    reviewCount: 67,
    area: 'Electrical Manufacturing Zone',
    foundedYear: 2002,
    teamSize: '220',
    brandColor: '#1d4ed8',
    trending: true,
    subCategories: ['Transformers', 'Switchgear', 'Cable Trays', 'Electrical Panels'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'LC', 'Credit (90 days)'],
    facilities: ['Manufacturing plant', 'Testing lab', 'Cable tray line'],
    deliveryOptions: ['Pan-India transport'],
    certifications: ['BIS Certified', 'ISO 9001', 'IEC 60076'],
    products: [
      { name: 'Distribution Transformer 250 kVA', category: 'Transformers', brand: 'PowerLine', priceMin: 285000, priceMax: 350000, availability: 'made_to_order', featured: true, variants: ['100 kVA', '250 kVA', '500 kVA', '1000 kVA'], specifications: [{ label: 'Voltage', value: '11kV/433V' }, { label: 'Type', value: 'Oil immersed' }, { label: 'Warranty', value: '5 years' }] },
      { name: 'Cable Tray (per meter)', category: 'Cable Trays', brand: 'PowerLine', priceMin: 450, priceMax: 1200, availability: 'in_stock', variants: ['Ladder', 'Perforated', 'Trough'], specifications: [{ label: 'Material', value: 'GI/SS' }, { label: 'Width', value: '100-600mm' }] },
    ],
    services: [],
  },
  {
    name: 'AgroNutri Fertilizers',
    tagline: 'B2B fertilizers & agricultural inputs',
    description: 'AgroNutri manufactures NPK fertilizers, micronutrients, bio-fertilizers and soil conditioners for agriculture departments, FPOs and large farms. Bulk supply with custom formulations.',
    category: 'Agricultural Equipment',
    verified: 'verified',
    rating: 4.3,
    reviewCount: 56,
    area: 'Agro Industrial Zone',
    foundedYear: 2008,
    teamSize: '85',
    brandColor: '#65a30d',
    subCategories: ['NPK Fertilizers', 'Micronutrients', 'Bio-fertilizers', 'Soil Conditioners'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30 days)'],
    facilities: ['Manufacturing plant', 'Lab testing', 'Bulk storage'],
    deliveryOptions: ['Pan-India', 'Dealer network'],
    certifications: ['FCO Certified', 'ISO 9001'],
    products: [
      { name: 'NPK 19-19-19 Water Soluble (25kg bag)', category: 'NPK Fertilizers', brand: 'AgroNutri', priceMin: 1800, priceMax: 2200, availability: 'in_stock', featured: true, variants: ['25kg', '50kg'], specifications: [{ label: 'Grade', value: '19-19-19' }, { label: 'Solubility', value: '100%' }] },
    ],
    services: [],
  },
  {
    name: 'CoolChain Cold Storage',
    tagline: 'B2B cold storage & temperature-controlled logistics',
    description: 'CoolChain operates 8 cold storage facilities across the region with temperature-controlled warehousing, blast freezing and reefer transport for pharma, food and agriculture B2B clients.',
    category: 'Logistics & Supply Chain',
    verified: 'verified',
    rating: 4.6,
    reviewCount: 34,
    area: 'Logistics Hub',
    foundedYear: 2016,
    teamSize: '120',
    brandColor: '#0891b2',
    recentlyVerified: true,
    subCategories: ['Cold Storage', 'Reefer Transport', 'Blast Freezing', 'Warehousing'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Monthly contract'],
    facilities: ['8 cold storage facilities', 'Reefer fleet', 'Blast freezers', 'Temperature monitoring'],
    deliveryOptions: ['Pan-India reefer'],
    certifications: ['ISO 9001', 'FSSAI', 'WHO GDP'],
    products: [],
    services: [
      { name: 'Cold Storage (per pallet/month)', pricing: '₹800 – ₹2,500', duration: 'Monthly', coverageArea: '8 cities', deliverables: ['Temperature-controlled storage', 'Inventory management', 'Temperature logs'] },
      { name: 'Reefer Transport', pricing: 'From ₹25/km', duration: '1–3 days', coverageArea: 'Pan-India', deliverables: ['Refrigerated truck', 'GPS tracking', 'Temperature log'] },
    ],
  },
  {
    name: 'PrecisionPlast Molds',
    tagline: 'B2B injection molds & plastic components',
    description: 'PrecisionPlast designs and manufactures injection molds, blow molds and plastic components for automotive, consumer goods and packaging industries. In-house mold flow analysis and rapid prototyping.',
    category: 'Chemicals & Plastics',
    verified: 'verified',
    rating: 4.5,
    reviewCount: 28,
    area: 'Plastics Industrial Zone',
    foundedYear: 2010,
    teamSize: '65',
    brandColor: '#0d9488',
    subCategories: ['Injection Molds', 'Plastic Components', 'Blow Molding', 'Rapid Prototyping'],
    languages: ['English', 'Hindi'],
    paymentMethods: ['NEFT', 'RTGS', 'Credit (30 days)'],
    facilities: ['Mold shop', 'Injection molding machines', 'CMM inspection', 'Design studio'],
    deliveryOptions: ['Pan-India', 'Export'],
    certifications: ['ISO 9001', 'IATF 16949'],
    products: [
      { name: 'Custom Injection Mold (per cavity)', category: 'Injection Molds', brand: 'PrecisionPlast', priceMin: 50000, priceMax: 500000, availability: 'made_to_order', featured: true, variants: ['Single cavity', 'Multi cavity', 'Family mold'], specifications: [{ label: 'Mold life', value: '500k+ shots' }, { label: 'Material', value: 'P20/H13/SS' }] },
    ],
    services: [
      { name: 'Mold Flow Analysis', pricing: 'From ₹15,000', duration: '2–3 days', coverageArea: 'Global', deliverables: ['Flow analysis report', 'Design optimization', 'Gate placement'] },
    ],
  },
]

const reviewsSeed = [
  { authorName: 'Rahul Mehta', rating: 5, title: 'Reliable B2B supplier', content: 'We have been sourcing from this company for 2 years. Consistent quality, on-time delivery and competitive pricing. Their B2B portal makes reordering seamless.', verified: true, helpful: 42 },
  { authorName: 'Priya Nair', rating: 4, title: 'Good quality, good service', content: 'Quality of products is excellent. Had a minor issue with a shipment but their team resolved it within 24 hours. Would recommend for B2B procurement.', verified: true, helpful: 18 },
  { authorName: 'Aman Verma', rating: 5, title: 'Excellent B2B partner', content: 'Transparent pricing and no unnecessary upselling. The team genuinely understands B2B requirements. Will continue to source from them.', verified: true, helpful: 27 },
  { authorName: 'Sneha Kapoor', rating: 5, title: 'Premium quality', content: 'Professional team, premium product quality. Their MOQ and bulk pricing works well for our manufacturing needs.', verified: false, helpful: 9 },
]

const reviewReplies = [
  'Thank you for your kind words! We are thrilled to be your B2B partner. — Management',
  'We appreciate the feedback and are always looking to improve our B2B service.',
  'Thank you for trusting us with your business needs!',
]

async function main() {
  console.log('Clearing existing data...')
  await db.review.deleteMany()
  await db.product.deleteMany()
  await db.service.deleteMany()
  await db.business.deleteMany()
  await db.category.deleteMany()
  await db.enquiry.deleteMany()
  await db.message.deleteMany()
  await db.inventoryItem.deleteMany()
  await db.order.deleteMany()
  await db.orderItem.deleteMany()
  await db.invoice.deleteMany()
  await db.customer.deleteMany()
  await db.expense.deleteMany()
  await db.staff.deleteMany()
  await db.subscription.deleteMany()
  await db.adminAction.deleteMany()

  console.log('Seeding B2B categories...')
  for (const c of categories) {
    await db.category.create({ data: { ...c, count: businesses.filter((b) => b.category === c.name).length } })
  }

  console.log('Seeding B2B businesses...')
  let idx = 0
  for (const b of businesses) {
    const lat = jitter(CENTER.lat, 0.08)
    const lng = jitter(CENTER.lng, 0.1)
    const seed = b.name.replace(/&/g, "and").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase()

    const cseed = (i: number) => categorySeed(b.category, i)
    const gallery = Array.from({ length: 6 }, (_, i) => img(`${cseed(i)}-${seed}`, 800, 600))

    const business = await db.business.create({
      data: {
        name: b.name,
        slug: seed,
        tagline: b.tagline,
        description: b.description,
        logo: img(`${cseed(0)}-logo-${seed}`, 200, 200),
        coverImage: img(`${cseed(1)}-cover-${seed}`, 1600, 600),
        gallery: JSON.stringify(gallery),
        category: b.category,
        subCategories: JSON.stringify(b.subCategories),
        verified: b.verified,
        rating: b.rating,
        reviewCount: b.reviewCount,
        lat,
        lng,
        address: `${b.area}, Meridian City ${100000 + idx * 7}`,
        area: b.area,
        city: 'Meridian City',
        state: 'Central Province',
        pincode: String(100000 + idx * 7),
        phone: `+91 9${String(800000000 + idx * 13579).slice(0, 9)}`,
        email: `contact@${seed}.in`,
        website: `https://${seed}.in`,
        whatsapp: `+91 9${String(800000000 + idx * 13579).slice(0, 9)}`,
        hours: JSON.stringify({
          days: [
            { day: 'Mon–Fri', open: '09:00', close: '18:00' },
            { day: 'Sat', open: '09:00', close: '14:00' },
            { day: 'Sun', open: 'Closed', close: 'Closed' },
          ],
          openNow: idx % 4 !== 3,
        }),
        isOpen: idx % 4 !== 3,
        foundedYear: b.foundedYear,
        teamSize: b.teamSize,
        languages: JSON.stringify(b.languages),
        paymentMethods: JSON.stringify(b.paymentMethods),
        facilities: JSON.stringify(b.facilities),
        deliveryOptions: JSON.stringify(b.deliveryOptions),
        social: JSON.stringify({ instagram: `@${seed}`, linkedin: `${seed}-official`, twitter: `@${seed}` }),
        certifications: JSON.stringify(b.certifications),
        awards: JSON.stringify((b as any).awards ?? []),
        viewCount: Math.floor(b.reviewCount * 8.4),
        responseTime: ['within an hour', 'within a few hours', 'within a day'][idx % 3],
        trending: b.trending ?? false,
        featured: b.featured ?? false,
        recentlyVerified: b.recentlyVerified ?? false,
        promotion: (b as any).promotion ? JSON.stringify((b as any).promotion) : null,
        announcement: idx % 3 === 0
          ? JSON.stringify({ title: 'New B2B catalog launched', body: 'Check our updated product catalog with bulk pricing tiers.', date: '2025-01-15' })
          : null,
        brandColor: b.brandColor,
        status: 'active',
        claimStatus: 'unclaimed',
      },
    })

    for (const p of b.products) {
      await db.product.create({
        data: {
          businessId: business.id,
          name: p.name,
          slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
          description: `${p.name} — supplied by ${b.name}. B2B pricing with bulk order discounts. ${b.certifications.join(', ')} certified.`,
          images: JSON.stringify(Array.from({ length: 4 }, (_, i) => img(`${cseed(i + 2)}-prod-${seed}-${i}`, 800, 600))),
          category: p.category,
          brand: p.brand,
          priceMin: p.priceMin,
          priceMax: p.priceMax,
          cost: Math.floor(p.priceMin * 0.7),
          sku: `SKU-${idx}-${Math.floor(Math.random() * 9000 + 1000)}`,
          variants: JSON.stringify(p.variants),
          specifications: JSON.stringify(p.specifications),
          availability: p.availability,
          stockQty: Math.floor(Math.random() * 500) + 50,
          reorderLevel: 20,
          documents: JSON.stringify(['Datasheet.pdf', 'Test Certificate.pdf', 'Safety Data Sheet.pdf']),
          faqs: JSON.stringify([
            { q: 'What is the minimum order quantity (MOQ)?', a: 'MOQ varies by product — please contact us for B2B bulk pricing.' },
            { q: 'Do you provide credit terms?', a: 'Yes, we offer 30/60/90 day credit to verified B2B buyers.' },
          ]),
          featured: p.featured ?? false,
          viewCount: Math.floor(Math.random() * 4000) + 200,
        },
      })
    }

    for (const s of b.services) {
      await db.service.create({
        data: {
          businessId: business.id,
          name: s.name,
          slug: s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
          description: `${s.name} by ${b.name}. ${b.description.slice(0, 120)}`,
          pricing: s.pricing,
          duration: s.duration,
          coverageArea: s.coverageArea,
          requirements: JSON.stringify(['Valid GST', 'Purchase order']),
          deliverables: JSON.stringify(s.deliverables),
          photos: JSON.stringify(Array.from({ length: 3 }, (_, i) => img(`${cseed(i + 3)}-svc-${seed}-${i}`, 800, 600))),
          faqs: JSON.stringify([{ q: 'How do I get a B2B quote?', a: 'Call us or request a quote through the platform.' }]),
        },
      })
    }

    const rcount = Math.min(6, Math.max(3, Math.floor(b.reviewCount / 50)))
    for (let i = 0; i < rcount; i++) {
      const r = reviewsSeed[i % reviewsSeed.length]
      await db.review.create({
        data: {
          businessId: business.id,
          authorName: r.authorName,
          authorAvatar: img(`avatar-${r.authorName.replace(/\s+/g, '-').toLowerCase()}`, 100, 100),
          rating: r.rating,
          title: r.title,
          content: r.content,
          photos: JSON.stringify(i % 2 === 0 ? [img(`${cseed(i + 4)}-review-${seed}`, 600, 400)] : []),
          verified: r.verified,
          helpful: r.helpful + i,
          businessReply: i % 2 === 0 ? reviewReplies[i % reviewReplies.length] : null,
          status: 'published',
          createdAt: new Date(Date.now() - i * 86400000 * 5),
        },
      })
    }

    // Create subscription
    await db.subscription.create({
      data: {
        businessId: business.id,
        plan: b.verified === 'enterprise' ? 'enterprise' : b.verified === 'premium' ? 'premium' : 'free',
        status: 'active',
        amount: b.verified === 'enterprise' ? 4999 : b.verified === 'premium' ? 999 : 0,
        billingCycle: 'monthly',
        startDate: new Date(),
      },
    })

    idx++
  }

  console.log(`Seeded ${businesses.length} B2B businesses.`)
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
